
name = "lang-utils"
version = "0.1.5"

[dependencies]

[dependencies.utils-file-system]
pkg="utils-file-system"
version="0.1.9"
type="conan"
options.shared = "True"
options.linux.fPIC = "True"
options.macos.fPIC = "True"
