
name = "lang-utils-static"
version = "0.0.16"

[dependencies]

[dependencies.utils-file-system]
pkg="utils-file-system"
version="0.0.16"
type="conan"
options.shared = "False"
options.linux.fPIC = "True"
options.macos.fPIC = "True"
