
name = "lang-utils"
version = "0.1.4"

[dependencies]

[dependencies.utils-file-system]
pkg="utils-file-system"
version="0.1.4"
type="conan"
options.shared = "True"
options.linux.fPIC = "True"
options.macos.fPIC = "True"
